// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sports.Infrastructure;

#nullable disable

namespace Sports.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250610145915_firstpush")]
    partial class firstpush
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sports.Models.Meta", b =>
                {
                    b.Property<int>("MetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetaId"));

                    b.Property<string>("SportId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportsId")
                        .HasColumnType("int");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("update_id")
                        .HasColumnType("bigint");

                    b.Property<bool>("update_idSpecified")
                        .HasColumnType("bit");

                    b.HasKey("MetaId");

                    b.HasIndex("SportsId");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("Sports.Models.NavigationInfo", b =>
                {
                    b.Property<int>("NavigationInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NavigationInfoId"));

                    b.Property<string>("SportId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportsId")
                        .HasColumnType("int");

                    b.Property<bool?>("has_standings")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_knockout")
                        .HasColumnType("bit");

                    b.Property<int>("key")
                        .HasColumnType("int");

                    b.Property<string>("value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NavigationInfoId");

                    b.HasIndex("SportsId");

                    b.ToTable("NavigationInfos");
                });

            modelBuilder.Entity("Sports.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("SportId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportsId")
                        .HasColumnType("int");

                    b.Property<int?>("ValuesId")
                        .HasColumnType("int");

                    b.Property<int>("key")
                        .HasColumnType("int");

                    b.HasKey("PropertyId");

                    b.HasIndex("SportsId");

                    b.HasIndex("ValuesId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Sports.Models.RelatedSportsEvent", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SportsId")
                        .HasColumnType("int");

                    b.Property<string>("depth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("navigation_infoNavigationInfoId")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("SportsId");

                    b.HasIndex("navigation_infoNavigationInfoId");

                    b.ToTable("RelatedSportsEvents");
                });

            modelBuilder.Entity("Sports.Models.Sport", b =>
                {
                    b.Property<int>("SportsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportsId"));

                    b.Property<int>("attendance")
                        .HasColumnType("int");

                    b.Property<bool>("attendanceSpecified")
                        .HasColumnType("bit");

                    b.Property<string>("away_participant_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direct_parent_sports_event_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<bool>("end_timeSpecified")
                        .HasColumnType("bit");

                    b.Property<int>("event_type_detail")
                        .HasColumnType("int");

                    b.Property<bool>("event_type_detailSpecified")
                        .HasColumnType("bit");

                    b.Property<string>("home_participant_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("parent_sports_event_ids")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("participant_type")
                        .HasColumnType("int");

                    b.Property<bool>("participant_typeSpecified")
                        .HasColumnType("bit");

                    b.Property<string>("phase_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("result_status")
                        .HasColumnType("int");

                    b.Property<bool>("result_statusSpecified")
                        .HasColumnType("bit");

                    b.Property<int?>("schedule_status")
                        .HasColumnType("int");

                    b.Property<bool>("schedule_statusSpecified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("scheduled_start_time_utc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("scheduled_start_time_utcSpecified")
                        .HasColumnType("bit");

                    b.Property<int?>("sibling_order")
                        .HasColumnType("int");

                    b.Property<bool>("sibling_orderSpecified")
                        .HasColumnType("bit");

                    b.Property<string>("sport_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sports_discipline_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sports_gender_id")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("sports_organization_ids")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start_date_local")
                        .HasColumnType("datetime2");

                    b.Property<bool>("start_date_localSpecified")
                        .HasColumnType("bit");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<bool>("statusSpecified")
                        .HasColumnType("bit");

                    b.Property<string>("translation_reference_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<string>("venue_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportsId");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("Sports.Models.States", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SportId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportsId")
                        .HasColumnType("int");

                    b.Property<string>("key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SportsId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Sports.Models.Value", b =>
                {
                    b.Property<int>("ValuesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValuesId"));

                    b.Property<string>("SportId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportsId")
                        .HasColumnType("int");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ValuesId");

                    b.HasIndex("SportsId");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Sports.Models.WeatherConditions", b =>
                {
                    b.Property<int>("WeatherConditionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeatherConditionsId"));

                    b.Property<string>("SportId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportsId")
                        .HasColumnType("int");

                    b.Property<int>("baseball_home_plate_wind_direction")
                        .HasColumnType("int");

                    b.Property<bool>("baseball_home_plate_wind_directionSpecified")
                        .HasColumnType("bit");

                    b.Property<double>("temperature_celsius")
                        .HasColumnType("float");

                    b.Property<bool>("temperature_celsiusSpecified")
                        .HasColumnType("bit");

                    b.Property<int>("temperature_fahrenheit")
                        .HasColumnType("int");

                    b.Property<bool>("temperature_fahrenheitSpecified")
                        .HasColumnType("bit");

                    b.Property<int>("weather_type")
                        .HasColumnType("int");

                    b.Property<bool>("weather_typeSpecified")
                        .HasColumnType("bit");

                    b.Property<int>("wind_direction")
                        .HasColumnType("int");

                    b.Property<bool>("wind_directionSpecified")
                        .HasColumnType("bit");

                    b.Property<double>("wind_speed_kilometers")
                        .HasColumnType("float");

                    b.Property<bool>("wind_speed_kilometersSpecified")
                        .HasColumnType("bit");

                    b.Property<int>("wind_speed_miles")
                        .HasColumnType("int");

                    b.Property<bool>("wind_speed_milesSpecified")
                        .HasColumnType("bit");

                    b.HasKey("WeatherConditionsId");

                    b.HasIndex("SportsId");

                    b.ToTable("WeatherConditions");
                });

            modelBuilder.Entity("Sports.Models.Meta", b =>
                {
                    b.HasOne("Sports.Models.Sport", "Sport")
                        .WithMany("Metas")
                        .HasForeignKey("SportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Sports.Models.NavigationInfo", b =>
                {
                    b.HasOne("Sports.Models.Sport", "Sport")
                        .WithMany("navigation_info")
                        .HasForeignKey("SportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Sports.Models.Property", b =>
                {
                    b.HasOne("Sports.Models.Sport", "Sport")
                        .WithMany("properties")
                        .HasForeignKey("SportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sports.Models.Value", "values")
                        .WithMany()
                        .HasForeignKey("ValuesId");

                    b.Navigation("Sport");

                    b.Navigation("values");
                });

            modelBuilder.Entity("Sports.Models.RelatedSportsEvent", b =>
                {
                    b.HasOne("Sports.Models.Sport", null)
                        .WithMany("related_sports_events")
                        .HasForeignKey("SportsId");

                    b.HasOne("Sports.Models.NavigationInfo", "navigation_info")
                        .WithMany()
                        .HasForeignKey("navigation_infoNavigationInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("navigation_info");
                });

            modelBuilder.Entity("Sports.Models.States", b =>
                {
                    b.HasOne("Sports.Models.Sport", "Sport")
                        .WithMany("state")
                        .HasForeignKey("SportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Sports.Models.Value", b =>
                {
                    b.HasOne("Sports.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Sports.Models.WeatherConditions", b =>
                {
                    b.HasOne("Sports.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Sports.Models.Sport", b =>
                {
                    b.Navigation("Metas");

                    b.Navigation("navigation_info");

                    b.Navigation("properties");

                    b.Navigation("related_sports_events");

                    b.Navigation("state");
                });
#pragma warning restore 612, 618
        }
    }
}
